/** Source-plane Desktop composition, with only a scripted model and test OS vault. */
import Subprocess from '@deepseek-ai/dsh-subprocess-local'
import { Context } from '@deepseek-ai/cordis'
import Loader from '@deepseek-ai/cordis-plugin-loader'
import Include from '@deepseek-ai/cordis-plugin-include'
import Storage from '@deepseek-ai/dsh-storage'
import * as Json from '@deepseek-ai/dsh-storage-json'
import * as Domain from '@deepseek-ai/dsh-storage-domain'
import Sessions from '@deepseek-ai/dsh-session'
import Agents from '@deepseek-ai/dsh-agent'
import Jsonl from '@deepseek-ai/dsh-session-persistence-jsonl'
import OrganizationContext from '@deepseek-ai/dsh-organization-context'
import { OrganizationConnection } from '@deepseek-ai/dsh-organization-connection'
import { LlmAdapter } from '@deepseek-ai/dsh-llm'
import OrganizationExecution, { executionInputsDigest, executionRequestSchema } from '@deepseek-ai/dsh-organization-execution'
import { bootOrganization } from '../src/organization-boot.ts'
import { openOrganizationExecution, readOrganizationExecution } from '../../desktop/src/organization-execution.ts'
import { OrganizationIntegration } from '../../desktop/src/organization-integration.ts'

export const kit = { Context, Loader, Include, LlmAdapter, OrganizationExecution, OrganizationConnection, executionInputsDigest, executionRequestSchema, bootOrganization, openOrganizationExecution, readOrganizationExecution, OrganizationIntegration, Subprocess, modules: new Map<string, unknown>([['storage', Storage], ['json', Json], ['domain', Domain], ['sessions', Sessions], ['agents', Agents], ['jsonl', Jsonl], ['context', OrganizationContext]]) }
